### ISSUE TITLE
Scans currently performed in non-equatorial coordinates

### ISSUE THREAD

**Issue by tianluyuan** [icecube/skymap_scanner#159]
Currently the scans are performed in a flipped equatorial coordinate system about the equator. This then is accounted for in the plotting/contour calculation [fixes](https://github.com/icecube/skymap_scanner/blob/863f7ce9f413818ad7b6b2edbdafc9ecde402413/skymap_scanner/utils/scan_result.py#L1182) are needed to produce a fits file in actual equatorial coordinates. It would be simpler and less confusing to perform the scan directly in equatorial coordinates.

https://github.com/icecube/skymap_scanner/blob/863f7ce9f413818ad7b6b2edbdafc9ecde402413/skymap_scanner/server/start_scan.py#L221
I think the above should just be `dec = numpy.pi/2.-dec`, in addition to similar updates in the plotting routines.

**Comment by mlincett** [comment]
I have noticed this in the past, as this was one of the inconsistencies between the realtime version and the cloud version.

I see no reason to keep it this way.

To me also `dec = numpy.pi/2.-dec` is kind of bad because the same variable takes two different meanings from one line to another, so please let's make this more self-explanatory.

**Comment by kjmeagher** [comment]
healpix calls this angle `theta` or `colatitude`. `codeclination` would also be a correct name. 

Also if we want to convert icecube to celestial without icetray i wrote this python module https://github.com/icecube/i3astropy
