### ISSUE TITLE
skymap_scanner should take simulation or data as input without issue

### ISSUE THREAD

**Issue by blaufuss** [icecube/skymap_scanner#7]
Not 100% sure this is not already true, but we should make sure this ability is not lost.

**Comment by ric-evans** [comment]
@tianluyuan is #83 sufficient to close this issue? If so, is there a way to detect whether an event is simulated? See https://github.com/icecube/skymap_scanner/blob/f1f10fda0e00994b08a7cc2ff3a2c335070968d4/skymap_scanner/utils/extract_json_message.py#L130

**Comment by tianluyuan** [comment]
Yes, I have been processing simulated events so to my mind this can be closed, or made more specific as to what might be missing still.

I'm not sure if there's a 100% full-proof way to detect if an event is simulated or not, since frame objects can be deleted and run/event ids can collide. The easiest might be to just check if the run-id falls within the data runs. I think that's another issue though.

**Comment by mlincett** [comment]
Since there is a lot of variability in how the frame structure can look like, I would avoid trying to be "too smart" here and just require the user to flag if an event is simulated.
