### ISSUE TITLE
Scanner output formats need to be improved/expanded

### ISSUE THREAD

**Issue by blaufuss** [icecube/skymap_scanner#9]
The current i3 file output from scans is difficult to interpret by non-experts, and ideally we need to be
able to automate "after the scan" workflows which are highly manual right now.

Suggestions here include:
* Output of a FITS skymap with key information in the header (ala catalog files in /data/ana/realtime/alert_catalog_v2/fits_files)

Potential after scan automation needs include:
* consumption by an alert DB
* consumption by I3Live
* generation of followup GCN/TACH notices

**Comment by blaufuss** [comment]
Another potential consumer is SCIMMA HopSkotch

**Comment by mlincett** [comment]
Note (mostly to myself) that some code is available from the [v2 alert catalog production scripts](https://github.com/icecube/alerts_processing).

**Comment by ric-evans** [comment]
@mlincett can we close this now? We have the `.npz` output file

**Comment by ric-evans** [comment]
We now also have `ScanResult.read_json()` and `ScanResult.to_json()` for communication with SkyDriver (#109)

Also, `scan_result.py` could be moved to a new `skymap_scanner_tools` repo for portability.

I'm closing this issue since output formats are A. much better now and B. further improvements are outside the scope of the scanner proper
